config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "url#root"

  namespace :admin do
    get "/", to: "dashboard#index", as: :dashboard
    get "/:target_url_id/urls", to: "dashboard#urls", as: :dashboard_urls
    get "/:short_url_id/events", to: "dashboard#url_events", as: :dashboard_url_events
  end

  namespace :api do
    resources :target_urls, only: %i[index show create destroy] do
      resources :short_urls, only: %i[index show create destroy]
    end
  end

  get "/url", to: "url#new", as: :new_url
  get "/url/:short_url_id", to: "url#show", as: :url
  post "/url", to: "url#create", as: :create_url

  get "/:slug", to: "url#redirect", as: :slug
end

app/controllers/admin/dashboard_controller.rb
# frozen_string_literal: true

module Admin
  class DashboardController < ApplicationController
    layout "admin"

    def index
      @target_urls = TargetUrl.order(created_at: :desc).all
    end

    def urls
      @target_url = TargetUrl.find(params.require(:target_url_id))
      @short_urls = @target_url.short_urls.order(created_at: :desc)
      @url_visits = short_url_aggregations(@short_urls)
    end

    def url_events
      @short_url_id = params.require(:short_url_id)
      events = UrlRedirectionEvent.where(short_url_id: @short_url_id).order(created_at: :desc)
      @url_events = events.offset(pagination[:offset]).limit(pagination[:page_size])
      @pagination = pagination.merge(total: events.count)
    end

    private

    def short_url_aggregations(short_urls)
      table = UrlRedirectionEvent.arel_table
      count_exp = table[:id].count.as("event_count")
      max_exp = table[:created_at].maximum.as("latest_event")

      result = UrlRedirectionEvent.where(short_url: short_urls)
                                  .group(:short_url_id)
                                  .pluck(:short_url_id, count_exp.to_sql, max_exp.to_sql)
      result.each_with_object({}) do |(short_url_id, event_count, latest_event), res|
        res[short_url_id] = {
          count: event_count,
          latest: latest_event.presence && Time.zone.parse(latest_event)
        }
      end
    end

    def pagination
      @pagination ||= begin
        page = begin
          params[:page]&.to_i
        rescue StandardError
          1
        end
        page ||= 1 # default page
        page_size = 5 # default page size
        {
          page: page,
          offset: (page - 1) * page_size,
          page_size: page_size
        }
      end
    end
  end
end

app/views/admin/dashboard/_short_urls.html.erb
<h3 class="text-sm font-medium">Shorten URLs</h2>
<ul role="list" class="divide-y divide-gray-100">
  <% short_urls.each do |short_url| %>
    <li class="flex flex-col gap-y-2 justify-between p-y-2">
      <div class="flex flex-col md:flex-row justify-between md:gap-x-3">
        <div class="flex-auto self-start md:self-center">
          <a 
            class="truncate text-xs leading-5 text-sky-600 hover:underline"
            href="<%= slug_url(short_url.slug) %>"
            target="_blank" 
            ><%= slug_url(short_url.slug) %></a>
        </div>
        <div class="shrink-0 flex flex-row gap-x-2 items-center self-end sm:self-center p-2 md:p-0">
          <% visit_count = url_visits.dig(short_url.id, :count) %>
          <% last_visit = url_visits.dig(short_url.id, :latest) %>
          <% if last_visit.present? %>
            <span class="text-sm font-semibold text-gray-700">last visited:</span>
            <span class="text-sm text-gray-500">
              <time datetime="<%= last_visit.iso8601 %>" 
                    data-controller="local-datetime" 
                    data-local-datetime-style-value="relative"/>
            </span>
          <% end %>
          <div class="flex items-center gap-x-1">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
              <path stroke-linecap="round" stroke-linejoin="round" d="M15.042 21.672 13.684 16.6m0 0-2.51 2.225.569-9.47 5.227 7.917-3.286-.672ZM12 2.25V4.5m5.834.166-1.591 1.591M20.25 10.5H18M7.757 14.743l-1.59 1.59M6 10.5H3.75m4.007-4.243-1.59-1.59" />
            </svg>
            <span class="text-sm text-gray-500">
              <% if visit_count&.positive? %>
                <%= pluralize(visit_count, "time") %>
              <% else %>
                no clicks yet
              <% end %>
            </span>
          </div>
        </div>
        <div class="shrink-0 flex items-center self-end sm:self-center">
          <div class="p-2 rounded-md text-lime-600 lg:hover:bg-lime-50">
            <a class="flex leading-5"
              href="<%= admin_dashboard_url_events_path(short_url.id) %>" 
              data-turbo-frame="short_url_<%= short_url.id %>_events">
              <span class="text-xs font-medium pr-2">Show Details</span>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
              </svg>
            </a>
          </div>
        </div>
      </div>
      <div>
        <%= turbo_frame_tag "short_url_#{short_url.id}_events" do %>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/admin/dashboard/_target_urls.html.erb
<h2 class="pt-2 text-lg font-bold">Target URLs</h2>
<ul role="list" class="divide-y divide-gray-100">
  <% target_urls.each do |target_url| %>
    <li class="flex flex-col gap-y-2 justify-between py-2">
      <div class="flex flex-col gap-y-3 md:flex-row justify-between md:gap-x-6">
        <div class="flex-auto min-w-0">
          <p class="line-clamp-2 text-base font-semibold leading-6 text-gray-900">
            <%= target_url.title %>
          </p>
          <a class="block truncate text-sm leading-5 text-sky-600 hover:underline"
            href="<%= target_url.external_url %>"
            target="_blank" 
            ><%= target_url.external_url %></a>
        </div>
        <div class="shrink-0 flex flex-row items-center self-end sm:flex-col sm:items-end">
          <p class="text-sm leading-5 text-gray-500 px-2">
            <time datetime="<%= target_url.created_at.iso8601 %>" 
              data-controller="local-datetime" data-local-datetime-time-value="false"/>
          </p>
          <div class="flex">
            <div class="rounded-md p-2 text-amber-600 lg:hover:bg-amber-50">
              <a class="flex leading-5" 
                href="<%= admin_dashboard_urls_path(target_url.id) %>" 
                data-turbo-frame="target_url_<%= target_url.id %>_short_urls">
                <span class="text-xs font-medium pr-2">Shorten URLs</span>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                  <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
                </svg>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div>
        <%= turbo_frame_tag "target_url_#{target_url.id}_short_urls" do %>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/admin/dashboard/_url_redirection_events.html.erb
<div class="sm:rounded-lg">
  <div class="overflow-x-auto ">
    <table class="w-full text-sm text-left text-gray-500">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50">
            <tr>
                <th scope="col" class="px-4 py-3">Timestamp</th>
                <th scope="col" class="px-4 py-3">User Agent</th>
                <th scope="col" class="px-4 py-3 min-w-40">IP Address</th>
                <th scope="col" class="px-4 py-3 min-w-24">Country</th>
                <th scope="col" class="px-4 py-3 min-w-24">City</th>
            </tr>
        </thead>
        <tbody>
            <% url_redirection_events.each do |event| %>
              <tr class="bg-white border-b">
                  <td class="px-4 py-2 text-nowrap">
                    <time datetime="<%= event.created_at.iso8601 %>" 
                      data-controller="local-datetime"
                      data-local-datetime-style-value="timestamp"/>
                  </td>
                  <td class="px-4 py-2"><%= event.user_agent %></td>
                  <td class="px-4 py-2"><%= event.ip_address %></td>
                  <td class="px-4 py-2"><%= event.country.presence || "-" %></td>
                  <td class="px-4 py-2"><%= event.city.presence || "-" %></td>
              </tr>
            <% end %>
        </tbody>
    </table>
  </div>
  <nav class="flex  flex-col flex-wrap items-center justify-center gap-y-2 md:flex-row md:justify-between pt-2" aria-label="Pagination">
    <div class="text-sm font-normal text-gray-500 block md:inline">
      Showing
      <span class="font-semibold text-gray-900">
        <% page_start = pagination[:offset] + 1 %>
        <% page_end = [pagination[:page] * pagination[:page_size], pagination[:total]].min %>
        <% if page_end - page_start > 0 %>
          <%= page_start %> - <%= page_end %>
        <% else %>
          <%= page_start %>
        <% end%>
      </span> of 
      <span class="font-semibold text-gray-900"><%= pagination[:total] %></span>
    </div>
    <form>
      <ul class="inline-flex -space-x-px text-sm font-medium h-8">
        <li>
            <% if pagination[:page] <= 1 %>
              <span class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg">Previous</a>
            <% else %>
              <a rel="prev"
              class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-900 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700"
              href="<%= admin_dashboard_url_events_path(short_url_id, page: pagination[:page] - 1) %>">Previous</a>
            <% end%>
        </li>
        <% pages = (pagination[:total] / pagination[:page_size].to_f).ceil %>
        <% (1..pages).each do |page| %>
          <li>
            <% if pagination[:page] == page %>
              <span aria-current="page" class="z-10 bg-indigo-600 text-white flex items-center justify-center px-3 h-8 ms-0 leading-tight border border-gray-300"><%= page %></a>
            <% else %>
              <a class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-900 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700"
              href="<%= admin_dashboard_url_events_path(short_url_id, page: page) %>"><%= page %></a>
            <% end%>
          </li>
        <% end %>
        <li>
            <% if pagination[:page] * pagination[:page_size] >= pagination[:total] %>
              <span class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg">Next</a>
            <% else %>
              <a rel="next"
              class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-900 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700"
              href="<%= admin_dashboard_url_events_path(short_url_id, page: pagination[:page] + 1) %>">Next</a>
            <% end%>
        </li>
      </ul>
    </form>
  </nav>
</div>

app/views/admin/dashboard/index.html.erb
<div class="w-full">
  <% if @target_urls&.present? %>
    <%= render partial: "target_urls", object: @target_urls %>    
  <% else %>
    <div>There are no URLs being shortened.</div>
  <% end %>
</div>

app/views/admin/dashboard/url_events.html.erb
<%= turbo_frame_tag "short_url_#{@short_url_id}_events" do %>
  <div class="w-full py-2">
    <% if @url_events&.present? %>
      <%= render partial: "url_redirection_events", 
                 object: @url_events, 
                 locals: { short_url_id: @short_url_id, pagination: @pagination } 
      %>
    <% else %>
      <div class="text-sm text-gray-500">There are no click events.</div>
    <% end %>
  </div>
<% end %>

app/views/admin/dashboard/urls.html.erb
<%= turbo_frame_tag "target_url_#{@target_url.id}_short_urls" do %>
  <div class="w-full px-4 py-2 sm:rounded-lg border border-gray-300">
    <% if @short_urls&.present? %>
      <%= render partial: "short_urls", object: @short_urls, locals: { url_visits: @url_visits } %>    
    <% else %>
      <div class="text-sm text-gray-500">No URLs being shortened.</div>
    <% end %>
  </div>
<% end %>