config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "url#root"

  namespace :admin do
    get "/", to: "dashboard#index", as: :dashboard
    get "/:target_url_id/urls", to: "dashboard#urls", as: :dashboard_urls
    get "/:short_url_id/events", to: "dashboard#url_events", as: :dashboard_url_events
  end

  namespace :api do
    resources :target_urls, only: %i[index show create destroy] do
      resources :short_urls, only: %i[index show create destroy]
    end
  end

  get "/url", to: "url#new", as: :new_url
  get "/url/:short_url_id", to: "url#show", as: :url
  post "/url", to: "url#create", as: :create_url

  get "/:slug", to: "url#redirect", as: :slug
end

app/controllers/url_controller.rb
# frozen_string_literal: true

class UrlController < ApplicationController
  include TrackUrlRedirection

  def root
    redirect_to(new_url_path)
  end

  def show
    @short_url = ShortUrl.find(params.require(:short_url_id))
  end

  def new; end

  def create
    input_url = params.require(:url)
    @short_url = UrlShortener.new(input_url).save!

    redirect_to url_path(@short_url.id), notice: "URL shortened successfully"
  rescue UrlValidator::UrlError => e
    flash.now[:alert] = e.message
    render :new, status: :unprocessable_entity
  end

  def redirect
    url_slug = params.require(:slug)
    short_url = (ShortUrl.find_by(slug: url_slug) if UrlSlugEncoder.default.slug_size >= url_slug.length)

    return redirect_to new_url_path, notice: "URL no longer available" if short_url.blank?

    track_url_redirection(short_url)
    redirect_to short_url.target_url.external_url, allow_other_host: true
  end
end

app/views/url/new.html.erb
<div class="flex flex-col w-full">
  <%= turbo_frame_tag "new_short_url" do %>
    <%= form_with url: create_url_path, class: "max-w-2xl" do |form| %>
      <% if notice %>
        <div class="py-2">
          <div class="bg-orange-100 border-l-4 border-orange-400 text-orange-700 px-4 py-2 max-w-2xlrelative" role="alert">
            <span class="block"><%= notice %></span>
          </div>
        </div>
      <% end %>
      <div class="flex flex-col sm:flex-row items-start sm:items-center py-2 gap-y-2">
        <%= form.label :url, "Enter a URL:", class: "min-w-28 font-medium text-gray-900" %>
        <%= form.url_field :url, 
          class: "border-0 border-b w-full px-0 md:px-2", 
          placeholder: "e.g. https://www.google.com",
          required: true
        %>
      </div>
      <% if alert %>
        <div class="py-2">
          <div class="bg-red-100 border-l-4 border-red-400 text-red-700 px-4 py-2 max-w-2xlrelative" role="alert">
            <span class="block"><%= alert %></span>
          </div>
        </div>
      <% end %>
      <div class="pt-4">
        <%= form.submit "Shorten URL", 
          class: "btn btn-primary block disabled:opacity-75 disabled:bg-slate-500" 
          %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/url/show.html.erb
<%= turbo_frame_tag "new_short_url" do %>
  <% if notice %>
    <div class="py-2">
      <div class="bg-emerald-100 border-l-4 border-emerald-400 text-emerald-700 px-4 py-2 max-w-2xlrelative" role="alert">
        <span class="block"><%= notice %></span>
      </div>
    </div>
  <% end %>
  <div id="<%= dom_id @short_url %>" class="flex flex-col w-full">
    <% target_url = @short_url.target_url %>

    <label for="<%= dom_id @short_url, :target %>" class="py-4">
      <span class="text-xl font-semibold">Your URL</span>
      <div id="<%= dom_id @short_url, :target %>">
        <a 
          class="text-sky-600 hover:underline" 
          href="<%= target_url.external_url %>" 
          target="_blank"><%= target_url.external_url %></a>
      </div>
    </label>
    
    <label for="<%= dom_id @short_url, :shorten %>" class="py-4">
      <span class="text-xl font-semibold">Shortened URL</span>
      <div class="font-light"><%= target_url.title %></div>
      <span id="<%= dom_id @short_url, :shorten %>">
        <a 
          class="text-sky-600 hover:underline" 
          href="<%= slug_url(slug: @short_url.slug) %>" 
          target="_blank"><%= slug_url(slug: @short_url.slug) %></a>
      </span>
    </label>

    <div class="pt-8">
      <a class="btn btn-primary" href="<%= new_url_path %>" data-turbo-frame="_top">Shorten another</a>
    </div>
  </div>
<% end %>